FROM rust:latest AS builder

WORKDIR /build
COPY . .

RUN cargo build --release --target x86_64-unknown-linux-gnu

FROM public.ecr.aws/lambda/provided:al2023

COPY --from=builder /build/target/x86_64-unknown-linux-gnu/release/create_user ${LAMBDA_RUNTIME_DIR}/bootstrap

CMD ["bootstrap"]